version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: Aaldea1604
      POSTGRES_DB: Preu_TopEducation
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
  app1:
    container_name: preu_topeducation_ti_1
    image: aaldeao/preu_topeducation
    ports:
      - "8091:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Preu_TopEducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aaldea1604
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  app2:
    container_name: preu_topeducation_ti_2
    image: aaldeao/preu_topeducation
    ports:
      - "8092:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Preu_TopEducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aaldea1604
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  app3:
    container_name: preu_topeducation_ti_3
    image: aaldeao/preu_topeducation
    ports:
      - "8093:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Preu_TopEducation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aaldea1604
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres